version: "3.7"
services:
  nginx:
    build: "./.docker/nginx"
    ports:
      - "80:80"
    volumes:
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./public:/app/public"
    depends_on:
      - app

  app:
    build: "./.docker/php"
    working_dir: "/app"
    volumes:
      - ".:/app"
      - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./storage/mysql:/var/lib/mysql"
      # - mysql-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}

  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
